/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Hotel = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'address' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const HotelContact = IDL.Record({
  'id' : IDL.Text,
  'contactType' : IDL.Text,
  'name' : IDL.Text,
  'hotelId' : IDL.Text,
  'phone' : IDL.Text,
  'remarks' : IDL.Text,
});
export const Time = IDL.Int;
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Player = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'jerseyNumber' : IDL.Text,
  'teamId' : IDL.Text,
  'position' : IDL.Text,
});
export const Room = IDL.Record({
  'beds' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'number' : IDL.Nat,
});
export const SupportStaff = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'addedAt' : Time,
  'teamId' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'assignedTo' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
});
export const Team = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'playerCount' : IDL.Nat,
  'sport' : IDL.Text,
  'staffCount' : IDL.Nat,
});
export const TeamTransport = IDL.Record({
  'id' : IDL.Text,
  'driverPhone' : IDL.Text,
  'driverAvailable' : IDL.Bool,
  'vehicleRegNumber' : IDL.Text,
  'teamId' : IDL.Text,
  'driverName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerRoomAssignment = IDL.Record({
  'playerId' : IDL.Text,
  'hotelId' : IDL.Text,
  'roomNumber' : IDL.Text,
  'teamId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TeamHotelAssignment = IDL.Record({
  'hotelId' : IDL.Text,
  'teamId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHotel' : IDL.Func([Hotel], [], []),
  'addHotelContact' : IDL.Func([HotelContact], [], []),
  'addNotification' : IDL.Func([Notification], [], []),
  'addPlayer' : IDL.Func([Player], [], []),
  'addRoom' : IDL.Func([Room], [], []),
  'addSupportStaff' : IDL.Func([SupportStaff], [], []),
  'addTask' : IDL.Func([Task], [], []),
  'addTeam' : IDL.Func([Team], [], []),
  'addTeamTransport' : IDL.Func([TeamTransport], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignHotelToTeam' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignPlayerRoom' : IDL.Func([PlayerRoomAssignment], [], []),
  'bookRoom' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'cancelTask' : IDL.Func([IDL.Text], [], []),
  'getAllAvailableRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getAllSupportStaff' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, SupportStaff))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHotel' : IDL.Func([IDL.Text], [IDL.Opt(Hotel)], ['query']),
  'getHotelContacts' : IDL.Func([IDL.Text], [IDL.Vec(HotelContact)], ['query']),
  'getPlayerRoomAssignments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlayerRoomAssignment)],
      ['query'],
    ),
  'getPlayersByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  'getSupportStaffByTeam' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SupportStaff)],
      ['query'],
    ),
  'getTeamHotelAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TeamHotelAssignment)],
      ['query'],
    ),
  'getTeamTransport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TeamTransport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeHotelContact' : IDL.Func([IDL.Text], [], []),
  'removePlayer' : IDL.Func([IDL.Text], [], []),
  'removePlayerRoomAssignment' : IDL.Func([IDL.Text], [], []),
  'removeSupportStaff' : IDL.Func([IDL.Text], [], []),
  'removeTeamHotelAssignment' : IDL.Func([IDL.Text], [], []),
  'removeTeamTransport' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateHotelContact' : IDL.Func([HotelContact], [], []),
  'updatePlayer' : IDL.Func([Player], [], []),
  'updateTeamName' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTeamPlayerCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateTeamStaffCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateTransportAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Hotel = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'address' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const HotelContact = IDL.Record({
    'id' : IDL.Text,
    'contactType' : IDL.Text,
    'name' : IDL.Text,
    'hotelId' : IDL.Text,
    'phone' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const Time = IDL.Int;
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Player = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'jerseyNumber' : IDL.Text,
    'teamId' : IDL.Text,
    'position' : IDL.Text,
  });
  const Room = IDL.Record({
    'beds' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'number' : IDL.Nat,
  });
  const SupportStaff = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'addedAt' : Time,
    'teamId' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'assignedTo' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
  });
  const Team = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'playerCount' : IDL.Nat,
    'sport' : IDL.Text,
    'staffCount' : IDL.Nat,
  });
  const TeamTransport = IDL.Record({
    'id' : IDL.Text,
    'driverPhone' : IDL.Text,
    'driverAvailable' : IDL.Bool,
    'vehicleRegNumber' : IDL.Text,
    'teamId' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerRoomAssignment = IDL.Record({
    'playerId' : IDL.Text,
    'hotelId' : IDL.Text,
    'roomNumber' : IDL.Text,
    'teamId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TeamHotelAssignment = IDL.Record({
    'hotelId' : IDL.Text,
    'teamId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHotel' : IDL.Func([Hotel], [], []),
    'addHotelContact' : IDL.Func([HotelContact], [], []),
    'addNotification' : IDL.Func([Notification], [], []),
    'addPlayer' : IDL.Func([Player], [], []),
    'addRoom' : IDL.Func([Room], [], []),
    'addSupportStaff' : IDL.Func([SupportStaff], [], []),
    'addTask' : IDL.Func([Task], [], []),
    'addTeam' : IDL.Func([Team], [], []),
    'addTeamTransport' : IDL.Func([TeamTransport], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignHotelToTeam' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignPlayerRoom' : IDL.Func([PlayerRoomAssignment], [], []),
    'bookRoom' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'cancelTask' : IDL.Func([IDL.Text], [], []),
    'getAllAvailableRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getAllHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getAllSupportStaff' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, SupportStaff))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHotel' : IDL.Func([IDL.Text], [IDL.Opt(Hotel)], ['query']),
    'getHotelContacts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HotelContact)],
        ['query'],
      ),
    'getPlayerRoomAssignments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlayerRoomAssignment)],
        ['query'],
      ),
    'getPlayersByTeam' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
    'getSupportStaffByTeam' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SupportStaff)],
        ['query'],
      ),
    'getTeamHotelAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TeamHotelAssignment)],
        ['query'],
      ),
    'getTeamTransport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TeamTransport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeHotelContact' : IDL.Func([IDL.Text], [], []),
    'removePlayer' : IDL.Func([IDL.Text], [], []),
    'removePlayerRoomAssignment' : IDL.Func([IDL.Text], [], []),
    'removeSupportStaff' : IDL.Func([IDL.Text], [], []),
    'removeTeamHotelAssignment' : IDL.Func([IDL.Text], [], []),
    'removeTeamTransport' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateHotelContact' : IDL.Func([HotelContact], [], []),
    'updatePlayer' : IDL.Func([Player], [], []),
    'updateTeamName' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTeamPlayerCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTeamStaffCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTransportAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };