/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Hotel {
  'id' : string,
  'name' : string,
  'available' : boolean,
  'address' : string,
  'capacity' : bigint,
}
export interface HotelContact {
  'id' : string,
  'contactType' : string,
  'name' : string,
  'hotelId' : string,
  'phone' : string,
  'remarks' : string,
}
export interface Notification {
  'id' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Player {
  'id' : string,
  'name' : string,
  'jerseyNumber' : string,
  'teamId' : string,
  'position' : string,
}
export interface PlayerRoomAssignment {
  'playerId' : string,
  'hotelId' : string,
  'roomNumber' : string,
  'teamId' : string,
}
export interface Room {
  'beds' : bigint,
  'isAvailable' : boolean,
  'number' : bigint,
}
export interface SupportStaff {
  'id' : string,
  'name' : string,
  'role' : string,
  'addedAt' : Time,
  'teamId' : string,
}
export interface Task {
  'id' : string,
  'assignedTo' : string,
  'dueDate' : Time,
  'description' : string,
}
export interface Team {
  'id' : string,
  'name' : string,
  'playerCount' : bigint,
  'sport' : string,
  'staffCount' : bigint,
}
export interface TeamHotelAssignment { 'hotelId' : string, 'teamId' : string }
export interface TeamTransport {
  'id' : string,
  'driverPhone' : string,
  'driverAvailable' : boolean,
  'vehicleRegNumber' : string,
  'teamId' : string,
  'driverName' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHotel' : ActorMethod<[Hotel], undefined>,
  'addHotelContact' : ActorMethod<[HotelContact], undefined>,
  'addNotification' : ActorMethod<[Notification], undefined>,
  'addPlayer' : ActorMethod<[Player], undefined>,
  'addRoom' : ActorMethod<[Room], undefined>,
  'addSupportStaff' : ActorMethod<[SupportStaff], undefined>,
  'addTask' : ActorMethod<[Task], undefined>,
  'addTeam' : ActorMethod<[Team], undefined>,
  'addTeamTransport' : ActorMethod<[TeamTransport], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignHotelToTeam' : ActorMethod<[string, string], undefined>,
  'assignPlayerRoom' : ActorMethod<[PlayerRoomAssignment], undefined>,
  'bookRoom' : ActorMethod<[string, bigint], string>,
  'cancelBooking' : ActorMethod<[bigint, string], undefined>,
  'cancelTask' : ActorMethod<[string], undefined>,
  'getAllAvailableRooms' : ActorMethod<[], Array<Room>>,
  'getAllHotels' : ActorMethod<[], Array<Hotel>>,
  'getAllSupportStaff' : ActorMethod<[], Array<[string, SupportStaff]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHotel' : ActorMethod<[string], [] | [Hotel]>,
  'getHotelContacts' : ActorMethod<[string], Array<HotelContact>>,
  'getPlayerRoomAssignments' : ActorMethod<
    [string],
    Array<PlayerRoomAssignment>
  >,
  'getPlayersByTeam' : ActorMethod<[string], Array<Player>>,
  'getSupportStaffByTeam' : ActorMethod<[string], Array<SupportStaff>>,
  'getTeamHotelAssignment' : ActorMethod<[string], [] | [TeamHotelAssignment]>,
  'getTeamTransport' : ActorMethod<[string], [] | [TeamTransport]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeHotelContact' : ActorMethod<[string], undefined>,
  'removePlayer' : ActorMethod<[string], undefined>,
  'removePlayerRoomAssignment' : ActorMethod<[string], undefined>,
  'removeSupportStaff' : ActorMethod<[string], undefined>,
  'removeTeamHotelAssignment' : ActorMethod<[string], undefined>,
  'removeTeamTransport' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHotelContact' : ActorMethod<[HotelContact], undefined>,
  'updatePlayer' : ActorMethod<[Player], undefined>,
  'updateTeamName' : ActorMethod<[string, string], undefined>,
  'updateTeamPlayerCount' : ActorMethod<[string, bigint], undefined>,
  'updateTeamStaffCount' : ActorMethod<[string, bigint], undefined>,
  'updateTransportAvailability' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];