/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: string;
    name: string;
    jerseyNumber: string;
    teamId: string;
    position: string;
}
export type Time = bigint;
export interface HotelContact {
    id: string;
    contactType: string;
    name: string;
    hotelId: string;
    phone: string;
    remarks: string;
}
export interface Task {
    id: string;
    assignedTo: string;
    dueDate: Time;
    description: string;
}
export interface Room {
    beds: bigint;
    isAvailable: boolean;
    number: bigint;
}
export interface PlayerRoomAssignment {
    playerId: string;
    hotelId: string;
    roomNumber: string;
    teamId: string;
}
export interface TeamHotelAssignment {
    hotelId: string;
    teamId: string;
}
export interface TeamTransport {
    id: string;
    driverPhone: string;
    driverAvailable: boolean;
    vehicleRegNumber: string;
    teamId: string;
    driverName: string;
}
export interface Hotel {
    id: string;
    name: string;
    available: boolean;
    address: string;
    capacity: bigint;
}
export interface Notification {
    id: string;
    message: string;
    timestamp: Time;
}
export interface SupportStaff {
    id: string;
    name: string;
    role: string;
    addedAt: Time;
    teamId: string;
}
export interface UserProfile {
    name: string;
}
export interface Team {
    id: string;
    name: string;
    playerCount: bigint;
    sport: string;
    staffCount: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHotel(hotel: Hotel): Promise<void>;
    addHotelContact(contact: HotelContact): Promise<void>;
    addNotification(notification: Notification): Promise<void>;
    addPlayer(player: Player): Promise<void>;
    addRoom(room: Room): Promise<void>;
    addSupportStaff(staff: SupportStaff): Promise<void>;
    addTask(task: Task): Promise<void>;
    addTeam(team: Team): Promise<void>;
    addTeamTransport(transport: TeamTransport): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignHotelToTeam(teamId: string, hotelId: string): Promise<void>;
    assignPlayerRoom(assignment: PlayerRoomAssignment): Promise<void>;
    bookRoom(teamId: string, roomId: bigint): Promise<string>;
    cancelBooking(roomId: bigint, teamId: string): Promise<void>;
    cancelTask(taskId: string): Promise<void>;
    getAllAvailableRooms(): Promise<Array<Room>>;
    getAllHotels(): Promise<Array<Hotel>>;
    getAllSupportStaff(): Promise<Array<[string, SupportStaff]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHotel(id: string): Promise<Hotel | null>;
    getHotelContacts(hotelId: string): Promise<Array<HotelContact>>;
    getPlayerRoomAssignments(teamId: string): Promise<Array<PlayerRoomAssignment>>;
    getPlayersByTeam(teamId: string): Promise<Array<Player>>;
    getSupportStaffByTeam(teamId: string): Promise<Array<SupportStaff>>;
    getTeamHotelAssignment(teamId: string): Promise<TeamHotelAssignment | null>;
    getTeamTransport(teamId: string): Promise<TeamTransport | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeHotelContact(contactId: string): Promise<void>;
    removePlayer(playerId: string): Promise<void>;
    removePlayerRoomAssignment(playerId: string): Promise<void>;
    removeSupportStaff(staffId: string): Promise<void>;
    removeTeamHotelAssignment(teamId: string): Promise<void>;
    removeTeamTransport(teamId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateHotelContact(contact: HotelContact): Promise<void>;
    updatePlayer(player: Player): Promise<void>;
    updateTeamName(teamId: string, name: string): Promise<void>;
    updateTeamPlayerCount(teamId: string, playerCount: bigint): Promise<void>;
    updateTeamStaffCount(teamId: string, count: bigint): Promise<void>;
    updateTransportAvailability(teamId: string, available: boolean): Promise<void>;
}
import type { Hotel as _Hotel, TeamHotelAssignment as _TeamHotelAssignment, TeamTransport as _TeamTransport, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHotel(arg0: Hotel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHotel(arg0);
            return result;
        }
    }
    async addHotelContact(arg0: HotelContact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHotelContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHotelContact(arg0);
            return result;
        }
    }
    async addNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0);
            return result;
        }
    }
    async addPlayer(arg0: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0);
            return result;
        }
    }
    async addRoom(arg0: Room): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoom(arg0);
            return result;
        }
    }
    async addSupportStaff(arg0: SupportStaff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupportStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupportStaff(arg0);
            return result;
        }
    }
    async addTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0);
            return result;
        }
    }
    async addTeam(arg0: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0);
            return result;
        }
    }
    async addTeamTransport(arg0: TeamTransport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamTransport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamTransport(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignHotelToTeam(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignHotelToTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignHotelToTeam(arg0, arg1);
            return result;
        }
    }
    async assignPlayerRoom(arg0: PlayerRoomAssignment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPlayerRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPlayerRoom(arg0);
            return result;
        }
    }
    async bookRoom(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookRoom(arg0, arg1);
            return result;
        }
    }
    async cancelBooking(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0, arg1);
            return result;
        }
    }
    async cancelTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTask(arg0);
            return result;
        }
    }
    async getAllAvailableRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableRooms();
            return result;
        }
    }
    async getAllHotels(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHotels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHotels();
            return result;
        }
    }
    async getAllSupportStaff(): Promise<Array<[string, SupportStaff]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportStaff();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotel(arg0: string): Promise<Hotel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotel(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotel(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelContacts(arg0: string): Promise<Array<HotelContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelContacts(arg0);
            return result;
        }
    }
    async getPlayerRoomAssignments(arg0: string): Promise<Array<PlayerRoomAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRoomAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRoomAssignments(arg0);
            return result;
        }
    }
    async getPlayersByTeam(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTeam(arg0);
            return result;
        }
    }
    async getSupportStaffByTeam(arg0: string): Promise<Array<SupportStaff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportStaffByTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportStaffByTeam(arg0);
            return result;
        }
    }
    async getTeamHotelAssignment(arg0: string): Promise<TeamHotelAssignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamHotelAssignment(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamHotelAssignment(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamTransport(arg0: string): Promise<TeamTransport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamTransport(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamTransport(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeHotelContact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHotelContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHotelContact(arg0);
            return result;
        }
    }
    async removePlayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayer(arg0);
            return result;
        }
    }
    async removePlayerRoomAssignment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayerRoomAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayerRoomAssignment(arg0);
            return result;
        }
    }
    async removeSupportStaff(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSupportStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSupportStaff(arg0);
            return result;
        }
    }
    async removeTeamHotelAssignment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamHotelAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamHotelAssignment(arg0);
            return result;
        }
    }
    async removeTeamTransport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamTransport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamTransport(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateHotelContact(arg0: HotelContact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotelContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotelContact(arg0);
            return result;
        }
    }
    async updatePlayer(arg0: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0);
            return result;
        }
    }
    async updateTeamName(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamName(arg0, arg1);
            return result;
        }
    }
    async updateTeamPlayerCount(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamPlayerCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamPlayerCount(arg0, arg1);
            return result;
        }
    }
    async updateTeamStaffCount(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamStaffCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamStaffCount(arg0, arg1);
            return result;
        }
    }
    async updateTransportAvailability(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransportAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransportAvailability(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hotel]): Hotel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamHotelAssignment]): TeamHotelAssignment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamTransport]): TeamTransport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
